CREATE TABLE order_sheet (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    circle_id BIGINT NOT NULL,
    creator_id BIGINT NOT NULL,
    title VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL COMMENT 'SHARED / IN_PROGRESS / COMPLETED',
    share_token CHAR(12) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_share_token (share_token),
    KEY idx_circle (circle_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE order_item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sheet_id BIGINT NOT NULL,
    dish_name VARCHAR(64) NOT NULL,
    note VARCHAR(255) NULL,
    claimant_id BIGINT NULL,
    item_status VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN / CLAIMED / COOKING / DONE',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_sheet (sheet_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE dish (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    circle_id BIGINT NULL,
    user_id BIGINT NULL,
    name VARCHAR(64) NOT NULL,
    recipe_id BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
